[book]
authors = ["Metal³ community"]
language = "en"
src = "src"
title = "Metal³ user-guide"

[preprocessor.releasetags]

[preprocessor.embed]
command = "mdbook-embed"

[output.html]
git-repository-url = "https://github.com/metal3-io/"
smart-punctuation = true
